#!/usr/bin/env python3
import colors as c
import time

print(c.clear)

x = 0.245542 

for n in range(12):
    print(c.red + 'badgers' + c.reset)
    time.sleep(x)

y = 3

for n in range(2)
    print(c.magenta + 'mushroom!!!!!' + c.reset)
    time.sleep(y)











