#!/usr/bin/env python3
import colors as c
import random

print(c.clear)

sides = []


sides.append('''
 _______       
|       |
|   0   |
|       |
|_______|
''')



sides.append('''
 _______       
|       |
|  0 0  |
|       |
|_______|
''')

sides.append('''
 _______       
|       |
|  0 0  |
|   0   |
|_______|
''')


sides.append('''
 _______       
|       |
|  0 0  |
|  0 0  |
|_______|
''')

sides.append('''
 _______       
|  0 0  |
|   0   |
|  0 0  |
|_______|
''')

sides.append('''
 _______       
|  0 0  |
|  0 0  |
|  0 0  |
|_______|
''')

while True:
    side = random.choice(sides)
    print(c.clear + c.random_color() + side)
    input() 



