#!/usr/bin/env python3

import sys
import colors as c

print(c.clear + c.red + 'Multiplication tables' + c.reset)

if len(sys.argv) < 2:

    number = input('Please enter a number, Durza: ')
else:
    number = sys.argv[1]



#hummmm
for count in range(12,0,-2):
    print(count, 'x', number, '=', int(number) * count)

























































































