#!/usr/bin/env python3

import colors as c
from utils import ask


which = ask("Fluffy or TheBaws?")
if which == 'fluffy':
    import fluffy as quiz
else:
    import thebaws as quiz

print(c.clear + quiz.intro)

quiz.q1()
quiz.q2()
quiz.q3()









