#!/usr/bin/env python3

import time
import colors as c


seconds = 0
hundredths = 0
minutes = 0
hours = 0
days = 0


while True:
    print(c.clear + c.red + '[Control-c to quit]' + c.reset,)
    print(seconds)
    print(hundredths)
    print(minutes)
    print(hours)
    print(days)
    time.sleep(0.01)
    hundredths += 1
    if minutes == 60:
        hours += 1
        minutes = 0
    if seconds == 60: 
        minutes += 1
        seconds = 0
    if hundredths == 100:
        seconds += 1
        hundredths = 0
    if hours == 24:
        days + 1
        hours + 0

















































































