#!/usr/bin/env python3
import colors as c
import random

print('''c.clear + c.green + "Welcome to the magic 8ball!!!! 
Enter Yo Questions My HomeBoyyyyyy! + c.reset
''')


answers = [ 
"Yes.",
"No.",
"Maybe.",
"Neva, Neva, Nevaah!!",
"When lil Wayne is president :p",  
"Catbert.",
'''Aint nobody got time
         Fo Dat!''',
"Whatju jus say 2 me?",
"When pigs invent a time machine.",
"Demon Squares.",
]


input("--> ")























