#!/usr/bin/env python3
import colors as c
import random

print('''"Welcome to the magic 8ball!!!! 
Enter Yo Questions My HomeBoyyyyyy!
''')


answers = [ 
"Yes.",
"No.",
"Maybe.",
"Neva, Neva, Nevaah!!",
"When lil Wayne is president :p",  
"Catbert.",
'''Aint nobody got time
         Fo Dat!''',
"Whatju jus say 2 me?",
"When pigs invent a time machine.",
"Demon Squares.",
"When Donald Trump's hair isn't classy.",

]


input("--> ")
answer = random.choice(answers)
print(answer)


























