#!/usr/bi/env python3
import colors as c
import random

print('''"Welcome to the magic 8ball!!!! 
Enter Yo Questions My HomeBoyyyyyy!
''')


answers = [ 
"Yes.",
"No.",
"Maybe so!",
"Neva, Neva, Nevaah!!",
"When lil Wayne is president :p",  
"Catbert.",
'''Aint nobody got time
         Fo Dat!''',
"Whatju jus say 2 me?",
"When pigs invent a time machine.",
"Until the end of time",
"Demon Squares.",
"When Donald Trump's hair isn't classy.",
"Don't ask me that.",
"Pahhhleez!!!",
"Muh hed esplode.",
"( ͡° ͜ʖ ͡°)",
":D",
"#Yeet",


def ask():
    question = input('> ' + c.random())



#Yoda Quote !   Try u must not no try only do     <----------------   LOOOOK
try:
    
    while True:
        if "doom" in question or "death" in question or "die" in question:
            print(c.red + "Well that is verry morbid." + c.x)
        elif "love" in question:
            print(c.magenta + "Love is beyond my power to predict" + c.x)
        else:
            answer = random.choice(answers)
            print(answer)
    
except KeyboardInterrupt: 
    exit() 
