#!/usr/bin/env python3
import colors as c

print(c.clear)

x=0.1242424

for n in range(12)
    print(c.blue + 'Badgers' + c.reset)
    time.sleep = x

y=3

for n in range(2)
    print(c.red + 'Mushroom' + c.reset) 
    time.sleep = y



























