#!/usr/bin/env python3
import colors as c


ask = c.blue + "Hello there, what's your name?" + c.reset

name = input(ask)


if name == 'durza':
    print(c.magenta + 'Oh hi! Nice to meet you!' + c.reset)


elif name == 'ninja turtle':
    print(c.green + "Heroes in a half shell, TURTLE POWAH!!!!!!!!" + c.reset)


else:
    print(c.red + "Oh, it's you. 'leaves'" + c.reset) 
    





























